### ISSUE TITLE
App Crashing after update to 1.40.1 and 1.41.0

### ISSUE THREAD

**Issue by MartinWahnschaffeSymeda** [hzi-braunschweig/SORMAS-Project#2212]
### Bug Description
Process: de.symeda.sormas.app, PID: 5204
    java.lang.NoClassDefFoundError: Failed resolution of: Lorg/slf4j/LoggerFactory;
        at de.symeda.sormas.api.Language.fromLocaleString(Language.java:85)
        at de.symeda.sormas.app.LocaleManager.initializeI18nProperties(LocaleManager.java:21)
        at de.symeda.sormas.app.SormasApplication.onCreate(SormasApplication.java:63)
        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1024)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5361)
        at android.app.ActivityThread.-wrap2(ActivityThread.java)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1528)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6077)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:866)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:756)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "org.slf4j.LoggerFactory" on path: DexPathList[[zip file "/system/framework/android.test.runner.jar", zip file "/data/app/de.symeda.sormas.app-2/base.apk"],nativeLibraryDirectories=[/data/app/de.symeda.sormas.app-2/lib/x86, /system/lib, /vendor/lib]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:380)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at de.symeda.sormas.api.Language.fromLocaleString(Language.java:85) 
        at de.symeda.sormas.app.LocaleManager.initializeI18nProperties(LocaleManager.java:21) 
        at de.symeda.sormas.app.SormasApplication.onCreate(SormasApplication.java:63) 
        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1024) 
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5361) 
        at android.app.ActivityThread.-wrap2(ActivityThread.java) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1528) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:154) 
        at android.app.ActivityThread.main(ActivityThread.java:6077) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:866) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:756) 

### Steps to Reproduce
Run 1.41.0 app on a fresh device (may need a second start). User should not have selected a language.

### System Details
* Device: Android
* SORMAS version: 1.40.1 & 1.41.0

**Comment by Chinedar** [comment]
@MartinWahnschaffeSymeda You mean after update to 1.41.0?

**Comment by MartinWahnschaffeSymeda** [comment]
@Chinedar Both. We are not sure yet, but it's possible that this is not a problem for the Nigerian system, because it's configured differently.

**Comment by MartinWahnschaffeSymeda** [comment]
Ideally Language.fromLocaleString should have a fallback to the "parent" language.
E.g. when the locale is en-US the language en should be returned, because en-US is currently not part of the Language enum. 

Add a unit test for this.

**Comment by bernardsilenou** [comment]
Thanks to the team

**Comment by MateStrysewskeSym** [comment]
The problem here was that a logging class was used that does not exist in the mobile app.
